server:
  port: 8888
logging:
  path: logs
  file: userManager.log
spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.132:3306/course?characterEncoding=utf8&useSSL=true
    username: admin
    password: admin
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*

